### ISSUE TITLE
Metamask Error

### ISSUE THREAD

**Issue by Issybobo** [dappuniversity/millow#12]
Hi, am getting error anytime i want to confirm my transaction
![image](https://user-images.githubusercontent.com/110337578/211154258-8cc2a605-1055-48c8-b357-f9fb577eef8d.png)

**Comment by Walletsuppport** [comment]
> Hi, am getting error anytime i want to confirm my transaction
> ![image](https://user-images.githubusercontent.com/110337578/211154258-8cc2a605-1055-48c8-b357-f9fb577eef8d.png)
> 

@Issybobo We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Walletsuppport** [comment]
> Hi, am getting error anytime i want to confirm my transaction
> ![image](https://user-images.githubusercontent.com/110337578/211154258-8cc2a605-1055-48c8-b357-f9fb577eef8d.png)
> 

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
