### ISSUE TITLE
Error in order to list properties/load NFT contracts into App

### ISSUE THREAD

**Issue by rohitscript** [dappuniversity/millow#6]
``` Im facing this problem !! ```
.
![image](https://user-images.githubusercontent.com/67726628/203579036-92f40efe-6041-40a9-85b3-3755470f33b0.png)
![image](https://user-images.githubusercontent.com/67726628/203579053-8a2c9c70-831d-4164-93c3-bc80b6616e38.png)

``` Properties Not Listed ```
.
![image](https://user-images.githubusercontent.com/67726628/203579080-345b86e0-d7a2-42cb-9388-4eefaab8f5b0.png)

**Comment by shantanusharma6079** [comment]
Hii i'm getting the same error have you resolved it?

**Comment by rohitscript** [comment]
Not Solved issue

**Comment by TanmayK95** [comment]
Please re-open this issue, it still persists
